# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24639883b2b5db4087a56a762e10026f8d1c01db65407352dd908c1ea37124a304934019296a0e4ddc268727b11d0dfe5a5eb3546142dca6aa1cc49583cb968d

test:
  secret_key_base: f63e44dd4902dad7c3600835eac156246122eac7ee86cf2dbbc4de5a80b7f3b915b934d715fc039ccf0191beb108532cc3d3b98c35f00aaa770c432f3bb82fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f63e44dd4902dad7c3600835eac156246122eac7ee86cf2dbbc4de5a80b7f3b915b934d715fc039ccf0191beb108532cc3d3b98c35f00aaa770c432f3bb82fcd
